artifact_uri: file:///C:/Users/moham/Downloads/MohamedWael-202201445-assighment 5/MohamedWael-202201445-assighment
  5/MohamedWael-202201445-assighment 2 - student A/mlruns_local/0/ef9e870a4d8f4d11b3f05880b3f177d7/artifacts
end_time: 1775929169236
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: ef9e870a4d8f4d11b3f05880b3f177d7
run_name: adventurous-shoat-97
source_name: ''
source_type: 4
source_version: ''
start_time: 1775929169092
status: 3
tags: []
user_id: moham
