artifact_uri: file:///C:/Users/moham/Downloads/MohamedWael-202201445-assighment 5/MohamedWael-202201445-assighment
  5/MohamedWael-202201445-assighment 2 - student A/mlruns_local/0/b0c2de37ef704e88af5f47a5a11a32a6/artifacts
end_time: 1775943404942
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: b0c2de37ef704e88af5f47a5a11a32a6
run_name: bold-mole-802
source_name: ''
source_type: 4
source_version: ''
start_time: 1775943404822
status: 3
tags: []
user_id: moham
