artifact_location: file:///C:/Users/moham/Downloads/MohamedWael-202201445-assighment
  5/MohamedWael-202201445-assighment 5/MohamedWael-202201445-assighment 2 - student
  A/mlruns_local/0
creation_time: 1775929168853
experiment_id: '0'
last_update_time: 1775929168853
lifecycle_stage: active
name: Default
trace_location: null
workspace: default
