artifact_uri: file:///C:/Users/moham/Downloads/MohamedWael-202201445-assighment 5/MohamedWael-202201445-assighment
  5/MohamedWael-202201445-assighment 2 - student A/mlruns_local/0/bb500a96b7bf4804b8875c3915246ed1/artifacts
end_time: 1775944043670
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: bb500a96b7bf4804b8875c3915246ed1
run_name: painted-ox-98
source_name: ''
source_type: 4
source_version: ''
start_time: 1775944043373
status: 3
tags: []
user_id: moham
